Pool list
RAMM-Finance/perpspot_interface pull request #37
Opened 2023-09-10 00:17 UTC by vpat95

- Removed two individual dropdown lists per currency and created a single pool list dropdown
- Search functionality will have to be refactored once datapipeline for pool list is setup/configured as the search currently validates one currency at a time which creates a conflict when searching for a pool of two currencies

2023-09-12 05:14 UTC, alanhwu requested changes
Naming/Icon-Ordering
Misc.

2023-09-12 05:14 UTC, alanhwu commented on src/components/swap/PoolSelector.tsx
Name/Icon entries inside the dropdown are reversed. You can fix it by changing here or by reversing the 2 icons that represent the pool.

2023-09-12 05:14 UTC, alanhwu commented on src/components/swap/TokenSelectorRow.tsx
Let's clean up the stray extra newlines that have been added throughout the files.

2023-09-12 12:26 UTC, vpat95 commented on src/components/swap/PoolSelector.tsx
Reversed props in the DoubleLogo component so that currency0 is the input currency and currency1 is the output. Originally this was reversed which caused the output to display in the first position and input to display second position.

2023-09-12 12:27 UTC, vpat95 commented on src/components/swap/TokenSelectorRow.tsx
done

2023-09-17 21:17 UTC, alanhwu approved these changes

2023-09-17 21:18 UTC, merged